version: "3"

services:
  mariadb:
    image: mariadb:11.4
    container_name: hive-mariadb
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: metastore
      MYSQL_USER: hive
      MYSQL_PASSWORD: hivepass
    ports:
      - "3307:3306"
    networks:
      hive-network:
        aliases:
          - mariadb
    volumes:
      - mariadb_data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "pidof mariadbd || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s

  metastore-standalone:
    image: apache/hive:4.0.1
    container_name: hive-metastore
    hostname: hive-metastore
    environment:
      SERVICE_NAME: metastore
      DB_DRIVER: mysql
      DB_TYPE: mysql
      SERVICE_OPTS: >-
        -Djavax.jdo.option.ConnectionDriverName=com.mysql.cj.jdbc.Driver
        -Djavax.jdo.option.ConnectionURL=jdbc:mysql://mariadb:3306/metastore?useSSL=false&allowPublicKeyRetrieval=true
        -Djavax.jdo.option.ConnectionUserName=hive
        -Djavax.jdo.option.ConnectionPassword=hivepass
        -Dhive.metastore.warehouse.dir=/user/hive/warehouse
        -Ddatanucleus.autoCreateSchema=true
        -Ddatanucleus.fixedDatastore=false
        -Dhive.metastore.schema.verification=false
        -Dhive.metastore.event.db.notification.api.auth=false
        -Dhive.log.dir=/opt/hive/logs
        -Dhive.querylog.location=/opt/hive/logs
    volumes:
      - ./hive-config:/opt/hive/conf
      - ./mysql-connector/mysql-connector-j-9.1.0.jar:/opt/hive/lib/mysql-connector-j-9.1.0.jar:ro
    ports:
      - "9083:9083"

  hiveserver2-standalone:
    image: apache/hive:4.0.1
    container_name: hive-server2
    depends_on:
      - metastore-standalone
    environment:
      SERVICE_NAME: hiveserver2
      IS_RESUME: true
      SERVICE_OPTS: >-
        -Djavax.jdo.option.ConnectionDriverName=org.mariadb.jdbc.Driver
        -Djavax.jdo.option.ConnectionURL=jdbc:mysql://mariadb:3306/metastore
        -Djavax.jdo.option.ConnectionUserName=hive
        -Djavax.jdo.option.ConnectionPassword=hivepass
        -Dhive.metastore.uris=thrift://metastore-standalone:9083
    volumes:
      - /home/leonardofm/.m2/repository/org/mariadb/jdbc/mariadb-java-client/3.4.0/mariadb-java-client-3.4.0.jar:/opt/hadoop/share/hadoop/common/lib/mariadb-java-client-3.4.0.jar:ro
      - ./conf/hive-site.xml:/opt/hive/conf/hive-site.xml
    ports:
      - "10000:10000"


networks:
  hive-network:
    driver: bridge

volumes:
  mariadb_data: